/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.Turma753Senac.View;

/**
 *
 * @author joelmir
 */
public class Empresa extends javax.swing.JFrame {

    /**
     * Creates new form Empresa
     */
    public Empresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Nome = new javax.swing.JLabel();
        jLabel_CNPJ = new javax.swing.JLabel();
        jLabel_RazaoSocial = new javax.swing.JLabel();
        jLabel_InscricaoEstadual = new javax.swing.JLabel();
        jLabel_InscricaoMunicipal = new javax.swing.JLabel();
        jLabel_Telefone = new javax.swing.JLabel();
        jLabel_Email = new javax.swing.JLabel();
        jLabel_Endereco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_Nome.setText("Nome");

        jLabel_CNPJ.setText("CNPJ");

        jLabel_RazaoSocial.setText("Razao Social");

        jLabel_InscricaoEstadual.setText("Ins. Estadual");

        jLabel_InscricaoMunicipal.setText("Ins. Municipal");

        jLabel_Telefone.setText("Telefone");

        jLabel_Email.setText("e-mail");

        jLabel_Endereco.setText("Endereco");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Nome)
                    .addComponent(jLabel_CNPJ)
                    .addComponent(jLabel_RazaoSocial)
                    .addComponent(jLabel_InscricaoEstadual)
                    .addComponent(jLabel_InscricaoMunicipal)
                    .addComponent(jLabel_Telefone)
                    .addComponent(jLabel_Email)
                    .addComponent(jLabel_Endereco))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Nome, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_CNPJ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_RazaoSocial)
                .addGap(18, 18, 18)
                .addComponent(jLabel_InscricaoEstadual)
                .addGap(18, 18, 18)
                .addComponent(jLabel_InscricaoMunicipal)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Telefone)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Email)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Endereco)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_CNPJ;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_Endereco;
    private javax.swing.JLabel jLabel_InscricaoEstadual;
    private javax.swing.JLabel jLabel_InscricaoMunicipal;
    private javax.swing.JLabel jLabel_Nome;
    private javax.swing.JLabel jLabel_RazaoSocial;
    private javax.swing.JLabel jLabel_Telefone;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
