/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.Turma753Senac.View;

import com.mycompany.Turma753Senac.Model.PessoaJuridica;
import javax.swing.JOptionPane;

/**
 *
 * @author joelmir
 */
public class Fornecedor extends javax.swing.JFrame {

    /**
     * Creates new form Empresa
     */
    public Fornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Nome = new javax.swing.JLabel();
        jLabel_CNPJ = new javax.swing.JLabel();
        jLabel_RazaoSocial = new javax.swing.JLabel();
        jLabel_InscricaoEstadual = new javax.swing.JLabel();
        jLabel_InscricaoMunicipal = new javax.swing.JLabel();
        jLabel_Telefone = new javax.swing.JLabel();
        jLabel_Email = new javax.swing.JLabel();
        jLabel_Endereco = new javax.swing.JLabel();
        jTextField_Nome = new javax.swing.JTextField();
        jTextField1_CNPJ = new javax.swing.JTextField();
        jTextFielD_RazaoSocial = new javax.swing.JTextField();
        jTextField_InsEstadual = new javax.swing.JTextField();
        jTextField_InsMunicipal = new javax.swing.JTextField();
        jTextField_Telefone = new javax.swing.JTextField();
        jTextField_Email = new javax.swing.JTextField();
        jTextField_Endereco = new javax.swing.JTextField();
        jLabel_Segmento = new javax.swing.JLabel();
        jTextField_Segmento = new javax.swing.JTextField();
        jLabel_titulo = new javax.swing.JLabel();
        jButton_Cadastrar = new javax.swing.JButton();
        jButton_sair = new javax.swing.JButton();
        jButton_Mostrar = new javax.swing.JButton();
        jButton_limpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fornecedor");

        jLabel_Nome.setText("Nome");

        jLabel_CNPJ.setText("CNPJ");

        jLabel_RazaoSocial.setText("Razao Social");

        jLabel_InscricaoEstadual.setText("Ins. Estadual");

        jLabel_InscricaoMunicipal.setText("Ins. Municipal");

        jLabel_Telefone.setText("Telefone");

        jLabel_Email.setText("e-mail");

        jLabel_Endereco.setText("Endereco");

        jLabel_Segmento.setText("Segmento");

        jLabel_titulo.setText("Cadastro Fornecedor:");

        jButton_Cadastrar.setText("Cadastrar");

        jButton_sair.setText("Sair");
        jButton_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_sairActionPerformed(evt);
            }
        });

        jButton_Mostrar.setText("Mostrar");
        jButton_Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_MostrarActionPerformed(evt);
            }
        });

        jButton_limpar.setText("Limpar");
        jButton_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_limparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_InscricaoEstadual)
                                    .addComponent(jLabel_InscricaoMunicipal))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_InsEstadual)
                                    .addComponent(jTextField_InsMunicipal)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_RazaoSocial)
                                    .addComponent(jLabel_Nome))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField_Nome, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                                        .addGap(3, 3, 3))
                                    .addComponent(jTextField1_CNPJ)
                                    .addComponent(jTextFielD_RazaoSocial)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_Telefone)
                                    .addComponent(jLabel_Segmento))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Segmento)
                                    .addComponent(jTextField_Endereco)
                                    .addComponent(jTextField_Email)
                                    .addComponent(jTextField_Telefone))))
                        .addGap(57, 57, 57))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_CNPJ)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Email)
                    .addComponent(jLabel_Endereco)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_titulo)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jButton_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(jButton_Mostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_limpar)
                .addGap(39, 39, 39)
                .addComponent(jButton_sair)
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Nome, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jTextField_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_CNPJ))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFielD_RazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_RazaoSocial))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_InsEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_InscricaoEstadual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_InscricaoMunicipal)
                    .addComponent(jTextField_InsMunicipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Telefone)
                    .addComponent(jTextField_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Email)
                    .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Endereco)
                    .addComponent(jTextField_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Segmento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Segmento))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton_sair))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Mostrar)
                            .addComponent(jButton_limpar))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_MostrarActionPerformed
        com.mycompany.Turma753Senac.Model.PessoaJuridica f = this.MostraFornecedor();
        JOptionPane.showMessageDialog(null,"Nome: "+f.getNome()+"\nCNPJ: "+f.getCnpj()+""
                +"\nRazão Social: "+f.getRazaoSocial()+"\nInscrição Estadual: "+f.getInscricaoEstadual()+""
                +"\nInscrição Municipal: "+f.getInscricaoMunicipal()+"\nTelefone: "+f.getTelefone()+"\n"
                + "Email: "+f.getEmail()+"\nEndereco: "+f.getEndereco()+"\nSegmento: "+f.getSegmento());
    }//GEN-LAST:event_jButton_MostrarActionPerformed

    private void jButton_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_limparActionPerformed
        jTextField_Nome.setText("");
        jTextField1_CNPJ.setText("");
        jTextFielD_RazaoSocial.setText("");
        jTextField_InsEstadual.setText("");
        jTextField_InsMunicipal.setText("");
        jTextField_Telefone.setText("");
        jTextField_Email.setText("");
        jTextField_Endereco.setText("");
        jTextField_Segmento.setText("");
    }//GEN-LAST:event_jButton_limparActionPerformed

    private void jButton_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sairActionPerformed
        boolean isClosed = false;
        // TODO add your handling code here:
            setVisible(isClosed);
    }//GEN-LAST:event_jButton_sairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fornecedor().setVisible(true);
            }
        });
    }
    public PessoaJuridica MostraFornecedor(){
       com.mycompany.Turma753Senac.Model.PessoaJuridica f =  new com.mycompany.Turma753Senac.Model.PessoaJuridica();
       
       f.setNome(jTextField_Nome.getText());
       f.setCnpj(jTextField1_CNPJ.getText());
       f.setRazaoSocial(jTextFielD_RazaoSocial.getText());
       f.setInscricaoEstadual(jTextField_InsEstadual.getText());
       f.setInscricaoMunicipal(jTextField_InsMunicipal.getText());
       f.setTelefone(jTextField_Telefone.getText());
       f.setEmail(jTextField_Email.getText());
       f.setEndereco(jTextField_Endereco.getText());
       f.setSegmento(jTextField_Segmento.getText());
       return f;
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Cadastrar;
    private javax.swing.JButton jButton_Mostrar;
    private javax.swing.JButton jButton_limpar;
    private javax.swing.JButton jButton_sair;
    private javax.swing.JLabel jLabel_CNPJ;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_Endereco;
    private javax.swing.JLabel jLabel_InscricaoEstadual;
    private javax.swing.JLabel jLabel_InscricaoMunicipal;
    private javax.swing.JLabel jLabel_Nome;
    private javax.swing.JLabel jLabel_RazaoSocial;
    private javax.swing.JLabel jLabel_Segmento;
    private javax.swing.JLabel jLabel_Telefone;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFielD_RazaoSocial;
    private javax.swing.JTextField jTextField1_CNPJ;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_Endereco;
    private javax.swing.JTextField jTextField_InsEstadual;
    private javax.swing.JTextField jTextField_InsMunicipal;
    private javax.swing.JTextField jTextField_Nome;
    private javax.swing.JTextField jTextField_Segmento;
    private javax.swing.JTextField jTextField_Telefone;
    // End of variables declaration//GEN-END:variables

    
}
